# flake8: noqa

# This file is autogenerated by /metadata-ingestion/scripts/avro_codegen.py
# Do not modify manually!

# fmt: off
from .....schema_classes import UpstreamClass
from .....schema_classes import UpstreamLineageClass


Upstream = UpstreamClass
UpstreamLineage = UpstreamLineageClass
# fmt: on
